### ISSUE TITLE
get deployment sorted

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/gip.rocks#1]
I made an app at Heroku and configured for auto-deployment on push to master over here at GitHub. First build is happening now, not sure if Pillow's JPEG and PNG dependencies will be resolved ...

**Comment by chadwhitacre** [comment]
I've purchased `gip.rocks`.

**Comment by chadwhitacre** [comment]
We don't need TLS for this.

**Comment by chadwhitacre** [comment]
We're live at http://gip-rocks.herokuapp.com/. :dancer: 

![screen shot 2015-09-10 at 1 26 45 am](https://cloud.githubusercontent.com/assets/134455/9780767/05e89be6-575b-11e5-841a-cc1d6d39f533.png)

413! ^^^

![test](https://cloud.githubusercontent.com/assets/134455/9780791/56822afe-575b-11e5-9a24-68fda42b9dd5.png)

![160](https://cloud.githubusercontent.com/assets/134455/9780796/61c4372c-575b-11e5-8b70-9fc388e4faf8.png)

![48](https://cloud.githubusercontent.com/assets/134455/9780799/661e5442-575b-11e5-8b02-9ac762851143.png)

**Comment by chadwhitacre** [comment]
We're at our limit of 10 domains at DNSimple for the $3/mo plan. Adding another would mean moving to their new pricing scheme, and we'd be at $8/mo. How about we drop `gittip.co`? :)

**Comment by chadwhitacre** [comment]
We're live on http://gip.rocks/. :-)

**Comment by chadwhitacre** [comment]
Did Pillow find `libjpeg`?

**Comment by chadwhitacre** [comment]
Yes. :-)

![screen shot 2015-09-10 at 1 41 28 am](https://cloud.githubusercontent.com/assets/134455/9780972/2650e396-575d-11e5-820e-59a79842de11.png)

**Comment by chadwhitacre** [comment]
Okay! We have an image processor! :-)

**Comment by chadwhitacre** [comment]
$7/mo

**Comment by chadwhitacre** [comment]
+$20/yr for the domain

**Comment by chadwhitacre** [comment]
Finances updated: http://inside.gratipay.com/appendices/finances.

**Comment by chadwhitacre** [comment]
P.S. I finally got to use Pillow! :-)

!m @aclark4life

http://gip.rocks/

**Comment by aclark4life** [comment]
Awesome!!! Wow that looks cool, nice work.

**Comment by chadwhitacre** [comment]
In action (locally) for Pillow ... :dancer: 

![screen shot 2015-09-10 at 7 51 09 am](https://cloud.githubusercontent.com/assets/134455/9787429/c195070a-5790-11e5-8c72-57eae4ef7ead.png)

![screen shot 2015-09-10 at 7 51 45 am](https://cloud.githubusercontent.com/assets/134455/9787432/cd5189a6-5790-11e5-8ec2-773b6eb66331.png)

**Comment by aclark4life** [comment]
Ah! Very cool

**Comment by kzisme** [comment]
@whit537 I'm just digging through stuff right now and wanted to say how neat this smaller project is.  :smile_cat:

**Comment by chadwhitacre** [comment]
:)
